version: "3.8"

services:
  bot:
    build: .
    container_name: element-poetry-bot-official
    restart: always
    environment:
      - QQ_APPID=${QQ_APPID}
      - QQ_SECRET=${QQ_SECRET}
      - QQ_TOKEN=${QQ_TOKEN}
      - ADMIN_QQS=${ADMIN_QQS:-}
    volumes:
      - ./data:/app/data
      - ./output:/app/output
